services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: prodmanager-keycloak
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ./infra/keycloak/realm-export:/opt/keycloak/data/import
      - kc_data:/opt/keycloak/data

  backend:
    build: .
    container_name: prodmanager-backend
    # espera o Keycloak ficar "ready" na porta de management 9000
    command: sh -lc 'until curl -fsS http://keycloak:9000/health/ready; do echo "aguardando Keycloak..."; sleep 2; done; python run.py'
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - keycloak
    volumes:
      - .:/app
    working_dir: /app


volumes:
  kc_data:
